name: Build and Deploy Frontend to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          cd store
          npm install

      - name: Start development server
        run: |
          cd store
          npm start &
        env:
          CI: true

      - name: Wait for server to be ready
        run: sleep 30

      - name: Run Cypress tests
        uses: cypress-io/github-action@v4
        with:
          start: npm start
          wait-on: http://localhost:3000
          wait-on-timeout: 60
          config-file: store/cypress.config.ts
        env:
          CI: true

      - name: Build React app
        run: |
          cd store
          CI=false npm run build

      - name: Build Docker image
        run: |
          docker build -f store/Dockerfile -t ribaso/frontend:latest store/

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image to Docker Hub
        run: docker push ribaso/frontend:latest
